#!/usr/bin/env python3
"""Deterministic campaign-manifest builder for /marketing:plan-campaign (BC-12587).

This is the PURE, hermetic computation core that `/marketing:plan-campaign`
delegates to in BOTH its normal and emit runs (ADR-028 D8 / Phase-2 grill DP2-1:
single source of truth, seam = pure-computation vs the IO boundary). Given the
campaign-defining inputs it computes — with NO MCP/network calls and NO real
Linear/SF/EB IDs (those don't exist yet) — and writes to `--out-dir`:

  * manifest.json  — the Step-7 cross-layer index (real IDs = null)
  * issues.json    — the per-issue payloads (container + 8 standard [+ 2 optional]),
                     cross-referenced BY INDEX (blockedBy:[indices]); the command's
                     IO layer resolves indices → real Linear IDs in its second pass
  * brief.md       — the slot-substituted brief skeleton

The command (orchestrator) owns the IO boundary in both runs: the Linear
collision read (re-invoking this builder with --disambiguator on a hit), all MCP
writes (milestone/issues/SF/EB), backfilling real IDs into the live records, the
two-call confirm gate, soft-fail SF, interactive prompts, and EB assignment.
Emit mode = run this builder → write to the sandbox → stop. Normal run = run this
builder → perform the MCP writes from its output → backfill IDs. Because emit
exercises the exact same deterministic code production uses, the per-PR behavioral
eval (BC-12589) is reproducible and needs no API key.

This builder also OWNS the HARD-FAIL validation (Phase-2 grill DP2-2) so the safety
invariants are unit-tested rather than living only in untested command prose:
Step 1b shape regexes, Step 2 canonicality (V/P/O membership + persona↔offer
target_personas), Step 3.2 slug regex, and Step 10.1 labs-gate. On any violation
it prints the canonical ERROR message to stderr and exits non-zero (2).

Stdlib-only per CLAUDE.md § Conventions (reuses the plugin's _shared readers); no
PyYAML, no jsonschema, no network. Same command+helper pattern as
canonicals_bootstrap.py / portfolio_snapshot.py.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _shared import canonicals_reader, slug_parts  # noqa: E402

# ── canonical constants ──────────────────────────────────────────────────

ENTITIES = ("nites", "supply", "labs", "cross-entity")
EB_WORKSPACES = ("emailbison-personal", "emailbison-b2b")
KEBAB_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
EMAIL_RE = re.compile(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$")
ISO_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
# Same canonical slug regex as /revops:create-sf-campaign Phase 1 + plan-campaign 3.2.
SLUG_RE = re.compile(r"^[a-z0-9-]+-fy\d{2}-m\d{2}(-v\d+)?$")

STANDARD_IDS = (1, 2, 3, 4, 5, 6, 7, 8)
SCHEMA_VERSION = 1
SCAFFOLDED_BY = "/marketing:plan-campaign"

# Inline fallback brief skeleton (mirror of plan-campaign Step 8a.4). Used when
# --brief-template is omitted (emit/eval path) so the artifact is deterministic;
# the command passes the handbook-fetched template in for a normal run.
INLINE_BRIEF_TEMPLATE = """# Campaign brief — {{slug}}

> Generated by `/marketing:plan-campaign` from the inline fallback template (handbook fetch failed OR pre-BC-10654 handbook pin lacking slot placeholders).
> Backfill from `handbook@main:marketing/go-to-market/templates/campaign-brief-template.md` if needed.

## 1. Overview

- **Entity**: {{entity}}
- **Vertical**: {{vertical_display}} ({{vertical}})
- **Persona**: {{persona_display}} — title cascade: {{persona_titles}}
- **Offer**: {{offer_display}} ({{offer}}) — posture: {{offer_posture}}
- **Launch date**: {{launch_date}}
- **Owner**: {{owner_email}}
- **Month**: {{month_display}}

## 2. Goals

<!-- OPERATOR-FILL: what does this campaign aim to achieve? Reference offer page goals + handbook ICP success metrics. -->

## 3. Audience

- **Canonical persona**: {{persona}} (display: {{persona_display}})
- **Title cascade**: {{persona_titles}}
- **Vertical ICP**: <!-- OPERATOR-FILL: paste/summarize from handbook/{{vertical}}/README.md ICP section -->

## 4. Messaging

<!-- OPERATOR-FILL: 1-2 angle hypotheses from /marketing:creative-angles + offer page value props -->

## 5. Channels

- **Primary**: cold email (Email Bison workspace `{{eb_workspace}}`)
- **Secondary**: <!-- OPERATOR-FILL: e.g. LinkedIn, paid retargeting -->

## 6. Assets

<!-- OPERATOR-FILL: deliverable spec, sample brief PDF, landing-page link, etc. -->

## 7. Budget

<!-- OPERATOR-FILL: $-spend + FTE-time estimates -->

## 8. Success metrics

<!-- OPERATOR-FILL: open rate / reply rate / acceptance rate / conversion-to-next-stage targets -->
"""


class BuildError(Exception):
    """A HARD-FAIL validation error carrying the canonical operator message."""


# ── sub-issue-template parsing (the BC-12564 reference file) ──────────────


def _parse_scalar(raw: str):
    """Parse one flat-YAML value: inline int-list, bool, int, or string."""
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        return [int(x.strip()) for x in inner.split(",")]
    if raw in ("true", "false"):
        return raw == "true"
    if re.fullmatch(r"-?\d+", raw):
        return int(raw)
    return raw.strip('"').strip("'")


def _parse_yaml_block(raw: str) -> dict:
    """Parse one fenced ```yaml block body into a flat dict.

    Mirrors the stdlib-only mini-parser in test_plan_campaign_contracts.py: a
    quoted value is read between its quotes (so a `#` inside a title is not
    truncated); a trailing ` #` comment is stripped only from unquoted scalars.
    """
    rec: dict = {}
    for line in raw.splitlines():
        line = line.rstrip()
        stripped = line.lstrip()
        if not stripped or stripped.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        val = val.strip()
        if val[:1] in ('"', "'"):
            quote = val[0]
            close = val.find(quote, 1)
            if close != -1:
                rec[key.strip()] = val[1:close]
            else:
                tail = val[1:]
                if " #" in tail:
                    tail = tail[: tail.index(" #")]
                rec[key.strip()] = tail.rstrip()
        else:
            if " #" in val:
                val = val[: val.index(" #")]
            rec[key.strip()] = _parse_scalar(val)
    return rec


def _extract_blockquote(chunk: str) -> str:
    """Extract the Description blockquote (the `>`-prefixed lines) from the text
    following a sub-issue's yaml block, stamped verbatim as the issue body."""
    lines: list[str] = []
    started = False
    for line in chunk.splitlines():
        s = line.rstrip()
        if s.startswith(">"):
            started = True
            content = s[1:]
            if content.startswith(" "):
                content = content[1:]
            lines.append(content)
        elif started and s.strip():
            break  # first non-EMPTY non-quote line ends it (blank separators tolerated)
    return "\n".join(lines).strip()


_YAML_WITH_DESC_RE = re.compile(
    r"```yaml\n(.*?)\n```(.*?)(?=\n### |\n## |\n---|\Z)", re.DOTALL
)


def parse_templates(templates_path: Path) -> dict[int, dict]:
    """Parse the sub-issue-template file into {id: {id,title,dueDate_offset_days,
    blockedBy,optional,labs_gated,description}}. Only fenced ```yaml blocks are
    records (the schema-doc header uses a ```text fence)."""
    text = templates_path.read_text(encoding="utf-8")
    by_id: dict[int, dict] = {}
    for m in _YAML_WITH_DESC_RE.finditer(text):
        rec = _parse_yaml_block(m.group(1))
        if "id" not in rec:
            continue
        rec["description"] = _extract_blockquote(m.group(2))
        by_id[int(rec["id"])] = rec
    return by_id


# ── helpers ──────────────────────────────────────────────────────────────


def _as_list(v) -> list[str]:
    """Normalize a target_personas value (inline-list string or list) to a list."""
    if isinstance(v, list):
        return [str(x) for x in v]
    if isinstance(v, str):
        s = v.strip()
        if s.startswith("[") and s.endswith("]"):
            inner = s[1:-1].strip()
            return [x.strip() for x in inner.split(",") if x.strip()] if inner else []
        return [s] if s else []
    return []


def _require_kebab(flag: str, value: str) -> None:
    if not KEBAB_RE.match(value):
        raise BuildError(f"ERROR: --{flag} must be strict kebab-case; got '{value}'")


# ── validation (HARD-FAIL invariants — Phase-2 grill DP2-2) ───────────────


def validate_inputs(a: argparse.Namespace, canon_dir: Path) -> None:
    """Apply the HARD-FAIL invariants. Raises BuildError with the canonical
    operator message on the first violation (mirrors plan-campaign Steps 1b/2/
    3.2/10.1). Order: shape → cross-entity presence → canonicality → labs-gate.
    (Slug regex is checked in compute_slug once the slug is assembled.)"""
    # Step 1b — shape invariants
    if a.entity not in ENTITIES:
        raise BuildError(
            f"ERROR: --entity must be one of [nites, supply, labs, cross-entity]; "
            f"got '{a.entity}'. Path-traversal guard."
        )
    if not (1 <= a.month <= 12):
        raise BuildError(f"ERROR: --month must be 1-12; got '{a.month}'")
    if not (2020 <= a.year <= 2099):
        raise BuildError(f"ERROR: --year must be 4-digit 2020-2099; got '{a.year}'")
    if not ISO_DATE_RE.match(a.launch_date) or not _is_real_date(a.launch_date):
        raise BuildError(
            f"ERROR: --launch-date must be ISO YYYY-MM-DD; got '{a.launch_date}'"
        )
    if a.eb_workspace not in EB_WORKSPACES:
        raise BuildError(
            f"ERROR: --eb-workspace must be emailbison-personal or emailbison-b2b; "
            f"got '{a.eb_workspace}'"
        )
    if a.owner_email and not EMAIL_RE.match(a.owner_email):
        raise BuildError(f"ERROR: --owner-email failed regex; got '{a.owner_email}'")
    if a.theme is not None and not KEBAB_RE.match(a.theme):
        raise BuildError(
            f"ERROR: --theme must be strict kebab-case (^[a-z0-9]+(-[a-z0-9]+)*$); "
            f"got '{a.theme}'. Theme flows into slug, filesystem paths, and SF "
            f"Campaign Name — must be safe for all three surfaces."
        )
    for flag, value in (("vertical", a.vertical), ("persona", a.persona), ("offer", a.offer)):
        if value is not None:
            _require_kebab(flag, value)
    if a.disambiguator is not None and a.disambiguator < 2:
        # v1 IS the base slug (no suffix); the command's collision loop only ever
        # passes attempt >= 2. A negative/zero/one value would otherwise produce a
        # malformed slug reported with the misleading canonicals-lint message.
        raise BuildError(
            f"ERROR: --disambiguator must be an integer >= 2 (v1 is the base slug); "
            f"got '{a.disambiguator}'"
        )

    if a.entity == "cross-entity":
        # Cross-entity campaigns are theme-defined; V/P/O are optional metadata.
        if not a.theme:
            raise BuildError(
                "ERROR: --entity=cross-entity requires --theme (e.g. --theme=america-250).\n"
                "Cross-entity campaigns omit the (vertical, persona, offer) triple in favor of a "
                "campaign-defining theme slug. See docs/gtm-campaign-orchestration-README.md § 3.5 "
                "+ docs/decisions/012-gtm-campaign-unit.md."
            )
    else:
        # Step 2 — canonicality (non-cross-entity requires the full triple)
        if not (a.vertical and a.persona and a.offer):
            raise BuildError(
                "ERROR: --vertical, --persona, and --offer are required for a "
                f"'{a.entity}' campaign (only --entity=cross-entity may omit them)."
            )
        _validate_canonicality(a, canon_dir)

    # Step 10.1 — labs-gate
    if a.situation_mining and a.entity != "labs":
        raise BuildError(
            "ERROR: --situation-mining is a Brite Labs framework (per "
            "docs/gtm-campaign-orchestration-README.md § 3.5).\n"
            f"You passed --situation-mining with --entity={a.entity}. Either drop the "
            "flag, OR re-run with --entity=labs."
        )


def _is_real_date(s: str) -> bool:
    try:
        date.fromisoformat(s)
        return True
    except ValueError:
        return False


def _validate_canonicality(a: argparse.Namespace, canon_dir: Path) -> None:
    verticals = canonicals_reader.load_canonicals_verticals(canon_dir)
    if a.vertical not in verticals:
        raise BuildError(
            f"ERROR: Vertical '{a.vertical}' is not in canonicals "
            f"({canon_dir}/_manifest.yaml).\n"
            "Either correct the slug, OR add it via /marketing:new-vertical (BC-8725).\n"
            f"Current canonical verticals: {', '.join(verticals)}"
        )
    vdoc = canonicals_reader.load_vertical(canon_dir, a.vertical)
    if not vdoc:
        raise BuildError(
            f"ERROR: Vertical '{a.vertical}' YAML file not found in {canon_dir}."
        )
    persona_slugs = [p.get("slug") for p in vdoc.get("personas", []) if isinstance(p, dict)]
    if a.persona not in persona_slugs:
        listed = ", ".join(s for s in persona_slugs if s) or "<empty>"
        raise BuildError(
            f"ERROR: Persona '{a.persona}' is not defined for vertical '{a.vertical}' "
            f"in {a.vertical}.yaml.\n"
            "Either correct the slug, OR add it via /marketing:new-persona (BC-8725).\n"
            f"Current canonical personas: {listed}"
        )
    offers = {o.get("slug"): o for o in vdoc.get("offers", []) if isinstance(o, dict)}
    if a.offer not in offers:
        listed = ", ".join(s for s in offers if s) or "<empty>"
        raise BuildError(
            f"ERROR: Offer '{a.offer}' is not defined for vertical '{a.vertical}' "
            f"in {a.vertical}.yaml.\n"
            "Either correct the slug, OR add it via /marketing:new-offer (BC-8725).\n"
            f"Current canonical offers: {listed}"
        )
    target_personas = _as_list(offers[a.offer].get("target_personas"))
    if target_personas and a.persona not in target_personas:
        raise BuildError(
            f"ERROR: Offer '{a.offer}' targets personas [{', '.join(target_personas)}] "
            f"— '{a.persona}' is not in this list.\n"
            "Either pick a valid persona for this offer, OR update the offer's "
            "target_personas via PR."
        )


# ── computation ──────────────────────────────────────────────────────────


def compute_slug(a: argparse.Namespace) -> str:
    """Compute the campaign slug, fold in --disambiguator, and assert the
    canonical slug regex (Step 3.1 / 3.2)."""
    yy = f"{a.year % 100:02d}"
    mm = f"{a.month:02d}"
    if a.entity == "cross-entity":
        base = f"cross-entity-{a.theme}-fy{yy}-m{mm}"
    else:
        base = f"{a.vertical}-{a.persona}-{a.offer}-fy{yy}-m{mm}"
    slug = f"{base}-v{a.disambiguator}" if a.disambiguator is not None else base
    if not SLUG_RE.match(slug):
        raise BuildError(
            f"ERROR: Computed slug '{slug}' does not match canonical regex "
            r"^[a-z0-9-]+-fy\d{2}-m\d{2}(-v\d+)?$." + "\n"
            "This is upstream-canonicals-lint territory — file an issue against "
            "plugins/marketing/data/canonicals/."
        )
    return slug


def build_labels(a: argparse.Namespace, slug: str) -> list[str]:
    """The campaign label set (plan-campaign § 8a.6). Standard campaigns carry
    all 8; a cross-entity campaign without a V/P/O triple omits the
    vertical/persona/offer identity labels (the theme is the identity)."""
    labels = [f"slug:{slug}", f"entity:{a.entity}"]
    if a.vertical:
        labels.append(f"vertical:{a.vertical}")
    if a.persona:
        labels.append(f"persona:{a.persona}")
    if a.offer:
        labels.append(f"offer:{a.offer}")
    labels += [f"year:{a.year}", f"month:{a.month:02d}", "status:planning"]
    return labels


def build_issues(
    a: argparse.Namespace, slug: str, labels: list[str], templates: dict[int, dict]
) -> dict:
    """Build the container + per-issue payloads (8 standard + enabled optionals),
    with absolute dueDates (launch-date + offset) and blockedBy-by-INDEX."""
    launch = date.fromisoformat(a.launch_date)
    selected = list(STANDARD_IDS)
    if a.situation_mining:
        selected.append(9)
    if a.creative_angles:
        selected.append(10)

    issues = []
    for idx in selected:
        rec = templates.get(idx)
        if rec is None:
            raise BuildError(
                f"ERROR: sub-issue template #{idx} missing from the reference file."
            )
        for key in ("title", "dueDate_offset_days", "blockedBy"):
            if key not in rec:
                raise BuildError(
                    f"ERROR: sub-issue template #{idx} is missing required field "
                    f"'{key}' in the reference file."
                )
        if not isinstance(rec["dueDate_offset_days"], int):
            raise BuildError(
                f"ERROR: sub-issue template #{idx} dueDate_offset_days must be an "
                f"integer; got {rec['dueDate_offset_days']!r}."
            )
        offset = rec["dueDate_offset_days"]
        issues.append(
            {
                "index": idx,
                "title": rec["title"],
                "description": rec["description"],
                "dueDate": (launch + timedelta(days=offset)).isoformat(),
                "labels": labels,
                "blockedBy": list(rec.get("blockedBy", [])),
                "optional": bool(rec.get("optional", False)),
                "labs_gated": bool(rec.get("labs_gated", False)),
            }
        )

    container = {
        "title": slug,
        "description": (
            f"Campaign rollup for {slug} — see the milestone for brief content. "
            "Parent of the campaign sub-issue chain."
        ),
        "labels": labels,
    }
    return {"container": container, "issues": issues}


def build_manifest(a: argparse.Namespace, slug: str, created_at: str) -> dict:
    """Assemble manifest.json (plan-campaign Step 7 schema). Real Linear/SF/EB
    IDs are null — they don't exist until the command's IO layer creates them."""
    return {
        "schema_version": SCHEMA_VERSION,
        "slug": slug,
        "entity": a.entity,
        "vertical": a.vertical,
        "persona": a.persona,
        "offer": a.offer,
        "year": a.year,
        "month": a.month,
        "linear": {"milestone_id": None, "milestone_url": None, "project": "Brite GTM"},
        "salesforce": {"campaign_id": None, "campaign_name": slug},
        "email_bison": {
            "workspace": a.eb_workspace,
            "campaign_id": None,
            "campaign_name": slug,
            "launched_at": None,
        },
        "created_at": created_at,
        "scaffolded_by": SCAFFOLDED_BY,
    }


def build_brief(a: argparse.Namespace, slug: str, canon_dir: Path) -> str:
    """Slot-substitute the brief skeleton (Step 8a.3). Substitution is pure (here);
    the handbook `gh api` fetch is the command's IO concern. Unfilled slots stay
    literal `{{slot}}` for the brief author (Step 8a.3 contract)."""
    template = (
        Path(a.brief_template).read_text(encoding="utf-8")
        if a.brief_template
        else INLINE_BRIEF_TEMPLATE
    )
    slots = {
        "slug": slug,
        "entity": a.entity,
        "launch_date": a.launch_date,
        "owner_email": a.owner_email or "",
        "year": str(a.year),
        "month_display": slug_parts.format_window_label(a.year, a.month),
        "eb_workspace": a.eb_workspace,
    }
    if a.vertical:
        vdoc = canonicals_reader.load_vertical(canon_dir, a.vertical) or {}
        slots["vertical"] = a.vertical
        slots["vertical_display"] = vdoc.get("display", "")
        for p in vdoc.get("personas", []):
            if isinstance(p, dict) and p.get("slug") == a.persona:
                slots["persona"] = a.persona
                slots["persona_display"] = p.get("display", "")
                slots["persona_titles"] = ", ".join(_as_list(p.get("titles")))
        for o in vdoc.get("offers", []):
            if isinstance(o, dict) and o.get("slug") == a.offer:
                slots["offer"] = a.offer
                slots["offer_display"] = o.get("display", "")
                slots["offer_posture"] = o.get("posture", "")
    # Single regex pass (order-independent; never substitutes into already-injected
    # content) so an unfilled slot stays literal `{{slot}}` per the Step 8a.3 contract.
    return re.sub(r"\{\{(\w+)\}\}", lambda m: slots.get(m.group(1), m.group(0)), template)


# ── orchestration ─────────────────────────────────────────────────────────


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="build_manifest.py",
        description="Deterministic campaign-manifest builder for /marketing:plan-campaign (BC-12587).",
    )
    p.add_argument("--vertical")
    p.add_argument("--persona")
    p.add_argument("--offer")
    p.add_argument("--entity", required=True)
    p.add_argument("--month", required=True, type=int)
    p.add_argument("--year", required=True, type=int)
    p.add_argument("--launch-date", required=True, dest="launch_date")
    p.add_argument("--theme", default=None)
    p.add_argument("--eb-workspace", required=True, dest="eb_workspace")
    p.add_argument("--owner-email", default=None, dest="owner_email")
    p.add_argument("--situation-mining", action="store_true", dest="situation_mining")
    p.add_argument("--creative-angles", action="store_true", dest="creative_angles")
    p.add_argument("--disambiguator", type=int, default=None)
    p.add_argument("--created-at", default=None, dest="created_at")
    p.add_argument("--canonicals-dir", required=True, dest="canonicals_dir")
    p.add_argument("--templates", required=True)
    p.add_argument("--brief-template", default=None, dest="brief_template")
    p.add_argument("--out-dir", required=True, dest="out_dir")
    return p.parse_args(argv)


def main(argv: list[str]) -> int:
    a = parse_args(argv)
    canon_dir = Path(a.canonicals_dir)
    try:
        validate_inputs(a, canon_dir)
        slug = compute_slug(a)
        labels = build_labels(a, slug)
        templates = parse_templates(Path(a.templates))
        issues = build_issues(a, slug, labels, templates)
        created_at = a.created_at or datetime.now(timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        manifest = build_manifest(a, slug, created_at)
        brief = build_brief(a, slug, canon_dir)
    except BuildError as exc:
        sys.stderr.write(str(exc) + "\n")
        return 2

    out_dir = Path(a.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (out_dir / "issues.json").write_text(
        json.dumps(issues, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (out_dir / "brief.md").write_text(brief, encoding="utf-8")

    sys.stdout.write(
        json.dumps(
            {
                "ok": True,
                "slug": slug,
                "out_dir": str(out_dir),
                "artifacts": ["manifest.json", "issues.json", "brief.md"],
                "issue_count": len(issues["issues"]),
            }
        )
        + "\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))